### ISSUE TITLE
UI misalignments

### ISSUE THREAD

**Issue by fiatjaf** [fiatjaf/bisu#1] opened 2023-02-21 11:29 UTC
When you first run bisu (after following one person) all looks fine:
![2023-02-21-082457_1920x1080_scrot](https://user-images.githubusercontent.com/1653275/220332660-1b08e1c8-625a-47a0-8c92-5bf9255c690a.png)

But then if you scroll through the posts eventually a page change can cause this (the left column is not visible anymore):
![2023-02-21-082509_1920x1080_scrot](https://user-images.githubusercontent.com/1653275/220332655-75ffdb86-75cb-473f-b149-86a5056f89d3.png)

And then even the individual posts can get screwed (why is there a vertical space between npub and text?):
![2023-02-21-082525_912x433_scrot](https://user-images.githubusercontent.com/1653275/220332652-13adb101-c445-488b-a629-daccc15feab9.png)

And the overall page misalignment doesn't seem to be a requirement for individual posts misalignment (in this case I just resized the window and it fixed the overall misalignment, but the vertical spaces continue):
![2023-02-21-082540_955x517_scrot](https://user-images.githubusercontent.com/1653275/220332648-7911c7e2-d531-450f-af2e-f6af28a6323c.png)

**Comment by jeremyd** [comment] 2023-02-21 21:30
The problem seems to be in the width calculation.. by increasing the width, scrolling no longer gets all messed up in my testing.  demonstration here:  https://github.com/fiatjaf/bisu/compare/master...jeremyd:bisu:master

**Comment by jeremyd** [comment] 2023-02-21 21:53
Also, the gaps in the highlight have to do with when the pubkey (longform) + the date string being larger than the terminal width.

**Comment by fiatjaf** [comment] 2023-02-21 23:36
> The problem seems to be in the width calculation.. by increasing the width, scrolling no longer gets all messed up in my testing. demonstration here: master...jeremyd:bisu:master

Is there a rationale for this or is just not expressible in words?

**Comment by fiatjaf** [comment] 2023-02-21 23:36
> Also, the gaps in the highlight have to do with when the pubkey (longform) + the date string being larger than the terminal width.

How come? The pubkey + date are always the same length, right? Or not?

**Comment by jeremyd** [comment] 2023-02-22 00:01
I mean, on my screen, with this fix in place.. now i only see a gap when the date/time gets pushed to the next line on a narrower window size.. (ie, the time part is on the next line.)

**Comment by jeremyd** [comment] 2023-02-22 00:04
> > The problem seems to be in the width calculation.. by increasing the width, scrolling no longer gets all messed up in my testing. demonstration here: master...jeremyd:bisu:master
> 
> Is there a rationale for this or is just not expressible in words?

Yes, my guess is the width calculation you were doing there doesn't account for the view border drawing/padding characters.

**Comment by jeremyd** [comment] 2023-02-23 20:06
you didn't like this solution I take it..

**Comment by fiatjaf** [comment] 2023-02-23 20:38
Sorry, I just didn't have time to try it. Your explanation wasn't convincing, sounded more like a guess -- which is fine as long as it works.

**Comment by jeremyd** [comment] 2023-02-23 20:52
Ah, cool. Ya the UI stuff is tricky, it's time consuming like CSS is to figure out the right layouts.  I did a deep dive into the wordwrap library and all the calculations happening here.. it's not apparent from the change but I tested a lot of different things before settling on this small change.  The word wrapping seems to be doing the right thing. I burned out on it after just getting going with no docs or example configs prob spent about 4 hours for this small change so I was like, he's gonna hate this and it'd prob take 4 more hours just to probably end up with this same thing again.  Anyway, lemme know when you try it out..

**Comment by greensponge** [comment] 2023-02-24 18:44
Hello fiatjaf, I fixed the issue locally for me and made a PR. Please check and let me know if you get rid of this problem.

The reason for the misalignment (if I am correct) is that lipgloss is causing the list to run higher than the vertical height of the terminal. There could still be some adjustments that need to be made here, but please try out the code and observe if the issue is fixed for you.

**Comment by fiatjaf** [comment] 2023-02-25 19:27
@jeremyd I tried your fix and it didn't work at all: 
![2023-02-25-162708_1440x900_scrot](https://user-images.githubusercontent.com/1653275/221375945-780f4ac4-5f97-4b1b-8748-f3b8ce415ade.png)

**Comment by greensponge** [comment] 2023-02-25 20:25
Ah, we don't need the TextStyle bottom padding anymore in `note_item_delegate.go`. If we remove that then it won't dance anymore, I can create PR. I'll check for that last empty-feed issue as well for 100% completion on this.

**Comment by jeremyd** [comment] 2023-02-25 22:17
> @jeremyd I tried your fix and it didn't work at all: ![2023-02-25-162708_1440x900_scrot](https://user-images.githubusercontent.com/1653275/221375945-780f4ac4-5f97-4b1b-8748-f3b8ce415ade.png)

[Screencast from 2023-02-25 14-16-13.webm](https://user-images.githubusercontent.com/4072/221382015-c762e5bd-caad-4248-8026-daec8c93e7d1.webm)

Weird, it worked great in my terminal..

**Comment by fiatjaf** [comment] 2023-02-25 22:29
Weird. What pubkeys are you following there? I tried again with `npub180cvv07tjdrrgpa0j7j7tmnyl2yr6yr7l8j4s3evf6u64th6gkwsyjh6w6` and got the errors again after 5 or 6 pages, not sure.

**Comment by jeremyd** [comment] 2023-02-25 22:39
> Weird. What pubkeys are you following there? I tried again with `npub180cvv07tjdrrgpa0j7j7tmnyl2yr6yr7l8j4s3evf6u64th6gkwsyjh6w6` and got the errors again after maybe 8 or 9 pages, not sure.

Following myself (npub10npj3gydmv40m70ehemmal6vsdyfl7tewgvz043g54p0x23y0s8qzztl5h) and you..

**Comment by fiatjaf** [comment] 2023-02-25 22:43
https://user-images.githubusercontent.com/1653275/221382907-70be5de8-be2b-4ae8-952b-1360f5c50ca2.mp4

Hmm, actually it did fix the space between name and content, but didn't fix the overall UI misalignment.

**Comment by jeremyd** [comment] 2023-02-25 22:52
very strange.. one thing you could try is increasing the offset from 8 -> 10+ and see, i have a feeling it could be something with unicode being weird about 'counting' as a character in a width in various terminals... what relay list are you using?  i can see if i can repro by pulling down more content from your feed..

**Comment by fiatjaf** [comment] 2023-02-25 23:06
Changed to 10. It was working fine, but then I decided to try other window sizes. Most were working fine too, but this one had one bug at one specific page:
![2023-02-25-200548_1104x868_scrot](https://user-images.githubusercontent.com/1653275/221383635-1bff3cee-52c4-4dea-b535-30017e485dbc.png)
![2023-02-25-200541_1104x878_scrot](https://user-images.githubusercontent.com/1653275/221383636-ddafe467-6004-40dc-afbd-9f4def594dd5.png)

**Comment by jeremyd** [comment] 2023-02-25 23:17
Hm, yes I see this page now, it jumps on the page that has the long URL for nostrbuild image.. but it doesn't seem to mess up the other windows it extends the window to the right for that page and then goes back which seems like what it should do given wordwrap doesn't cut strings in half or anything.. I can't seem to get it to break further than that even with diff terminal sizes.  Using gnome-terminal TERM=xterm-256color

[Screencast from 2023-02-25 15-13-28.webm](https://user-images.githubusercontent.com/4072/221383902-3b6741f2-23b2-4abf-98d8-0f54b606119c.webm)

**Comment by greensponge** [comment] 2023-02-26 17:29
The last issue with really long links can be solved by adding `Width(m.Width()).` to the `TextStyle` print in `note_item_delegate.go -> Render(...)`.  Since we've been playing a bit of whack-a-mole with this I will check some more, but otherwise I'll make another PR soon.

**Comment by greensponge** [comment] 2023-02-26 19:43
Please check the PR before merging @fiatjaf in case there is something left to fix. This issue should be completely fixed now, but let's see if you can find anything first. Tested in Alacritty, Xterm and Xfce with no artifacts. I followed you, 0xtr and Dergigi.

**Comment by jeremyd** [comment] 2023-02-26 20:04
> Please check the PR before merging @fiatjaf in case there is something left to fix. This issue should be completely fixed now, but let's see if you can find anything first. Tested in Alacritty, Xterm and Xfce with no artifacts. I followed you, 0xtr and Dergigi.

nice fix, ya this works on my testing. :call_me_hand:

**Closed** 2023-02-27 00:02 UTC

**Comment by fiatjaf** [comment] 2023-02-27 00:05
@greensponge are you https://stacker.news/brynrussell?

**Comment by greensponge** [comment] 2023-02-27 04:57
> @greensponge are you https://stacker.news/brynrussell?

Yes, that's me 👍
